"""Pipeline context for passing state through validation phases.

This module defines the PipelineContext dataclass, which serves as a shared
state container passed through all pipeline phases during validation.
"""

from dataclasses import dataclass, field
from typing import Any

import polars as pl

from nyctea.engine.results import ErrorReportConfig, ValidationReport
from nyctea.schema.model import SchemaModel
from nyctea.types import AggregateEngine
from nyctea.validators.registry import Registry

__all__ = ["PipelineContext"]


@dataclass
class PipelineContext:
    """Shared state container for validation pipeline execution.

    This dataclass is passed through all pipeline phases, accumulating state
    and intermediate results as validation progresses.

    Attributes:
        data: The DataFrame/LazyFrame being validated (mutated by phases).
        original_data: Data after column resolution but before frame and column
            transformations, used for original null statistics.
        schema: The schema definition.
        registry: Validator registry for lookups.
        error_report_config: Configuration for error reporting detail.
        check_masks: Maps (column, check) to boolean mask column alias in data.
        internal_columns: Helper columns generated by phases, stripped before the result is returned.
        nullified_counts: Counts of nullified values per column.
        errors: Error DataFrame (built by ErrorReportingPhase).
        report: Final validation report (built by ReportGenerationPhase).
        metadata: Additional phase-specific metadata.
        aggregate_engine: Polars ``collect()`` engine for internal reduction-only
            aggregates (not for materializing rows). Decided once per ``validate()``
            call from ``schema.streaming_row_threshold`` before the pipeline runs,
            so every phase and post-pipeline step uses the same choice.

    Read column names through ``frame_schema()`` or ``get_column_names()`` rather
    than ``data.collect_schema()``. Resolving a LazyFrame's schema walks its whole
    plan, and the context caches the result per frame so repeated readers do not
    each pay for it.
    """

    # Input configuration
    data: pl.LazyFrame
    schema: SchemaModel
    registry: Registry
    error_report_config: ErrorReportConfig | None = None
    aggregate_engine: AggregateEngine = "in-memory"
    original_data: pl.LazyFrame | None = None

    # Tracking state (populated by phases)
    check_masks: dict[tuple[str, str], str] = field(default_factory=dict)  # (col, check) -> mask column alias
    internal_columns: set[str] = field(default_factory=set)  # generated helper columns, stripped before output
    nullified_counts: dict[str, int] = field(default_factory=dict)

    # Output (built by phases)
    errors: pl.DataFrame | None = None
    report: ValidationReport | None = None

    # Phase metadata (arbitrary additional data)
    metadata: dict[str, Any] = field(default_factory=dict)

    # Cache backing `frame_schema()`. Keyed on the frame object, never on a flag a
    # phase has to remember to set.
    _schema_of: pl.LazyFrame | None = field(default=None, repr=False, compare=False)
    _frame_schema: pl.Schema | None = field(default=None, repr=False, compare=False)

    def frame_schema(self) -> pl.Schema:
        """Resolve ``data``'s schema, once per change to the frame.

        Resolving a LazyFrame's schema walks its whole plan, so a phase that asks
        for column names twice pays for it twice. Phases replace ``data`` rather
        than mutating it, since every Polars operation returns a new frame, so the
        object's identity changes exactly when the plan does. Keying the cache on
        that identity means it refreshes itself and cannot go stale, which a flag a
        phase has to remember to clear could not promise.

        Returns:
            The Polars schema of the current data.
        """
        if self._schema_of is not self.data or self._frame_schema is None:
            self._schema_of = self.data
            self._frame_schema = self.data.collect_schema()
        return self._frame_schema

    def get_column_names(self) -> list[str]:
        """Get current column names from data."""
        return self.frame_schema().names()

    def set_metadata(self, key: str, value: Any) -> None:
        """Set phase-specific metadata.

        Args:
            key: Metadata key.
            value: Metadata value.
        """
        self.metadata[key] = value

    def get_metadata(self, key: str, default: Any = None) -> Any:
        """Get phase-specific metadata.

        Args:
            key: Metadata key.
            default: Default value if key not found.

        Returns:
            Metadata value or default.
        """
        return self.metadata.get(key, default)
