"""Pipeline context for passing state through validation phases.

This module defines the PipelineContext dataclass, which serves as a shared
state container passed through all pipeline phases during validation.
"""

from dataclasses import dataclass, field
from typing import Any

import polars as pl

from nyctea.engine.results import ErrorReportConfig, ValidationReport
from nyctea.schema.model import AggregateEngine, SchemaModel
from nyctea.validators.registry import Registry

__all__ = ["PipelineContext"]


@dataclass
class PipelineContext:
    """Shared state container for validation pipeline execution.

    This dataclass is passed through all pipeline phases, accumulating state
    and intermediate results as validation progresses.

    Attributes:
        data: The DataFrame/LazyFrame being validated (mutated by phases).
        original_data: Data after column resolution but before frame and column
            transformations, used for original null statistics.
        schema: The schema definition.
        registry: Validator registry for lookups.
        error_report_config: Configuration for error reporting detail.
        check_masks: Maps (column, check) to boolean mask column alias in data.
        internal_columns: Helper columns generated by phases, stripped before the result is returned.
        nullified_counts: Counts of nullified values per column.
        errors: Error DataFrame (built by ErrorReportingPhase).
        report: Final validation report (built by ReportGenerationPhase).
        metadata: Additional phase-specific metadata.
        aggregate_engine: Polars ``collect()`` engine for internal reduction-only
            aggregates (not for materializing rows). Decided once per ``validate()``
            call from ``schema.streaming_row_threshold`` before the pipeline runs,
            so every phase and post-pipeline step uses the same choice.
    """

    # Input configuration
    data: pl.LazyFrame
    schema: SchemaModel
    registry: Registry
    error_report_config: ErrorReportConfig | None = None
    aggregate_engine: AggregateEngine = "in-memory"
    original_data: pl.LazyFrame | None = None

    # Tracking state (populated by phases)
    check_masks: dict[tuple[str, str], str] = field(default_factory=dict)  # (col, check) -> mask column alias
    internal_columns: set[str] = field(default_factory=set)  # generated helper columns, stripped before output
    nullified_counts: dict[str, int] = field(default_factory=dict)

    # Output (built by phases)
    errors: pl.DataFrame | None = None
    report: ValidationReport | None = None

    # Phase metadata (arbitrary additional data)
    metadata: dict[str, Any] = field(default_factory=dict)

    def get_column_names(self) -> list[str]:
        """Get current column names from data."""
        return self.data.collect_schema().names()

    def set_metadata(self, key: str, value: Any) -> None:
        """Set phase-specific metadata.

        Args:
            key: Metadata key.
            value: Metadata value.
        """
        self.metadata[key] = value

    def get_metadata(self, key: str, default: Any = None) -> Any:
        """Get phase-specific metadata.

        Args:
            key: Metadata key.
            default: Default value if key not found.

        Returns:
            Metadata value or default.
        """
        return self.metadata.get(key, default)
